name: todoapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  rxdart: ^0.24.1
  flutter_time_picker_spinner: ^1.0.6+1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.28



  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
   
